name: Build C++ code

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build C++ code
        run: |
          cd src
          make
      # - name: Run tests
      #   run: |
      #     cd tests
      #     bash ./run_tests.sh
      #   env:
      #     CI: true
